apiVersion: v1
kind: Service
metadata:
  name: tom-backend
  namespace: tom

  labels:
    app: tom-backend

spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

  selector:
    app: tom-backend